language: go
go:
  - 1.6
  - 1.7
  - tip
install:
  - go get github.com/getsentry/raven-go
  - go get gopkg.in/natefinch/lumberjack.v2
script: go test -v ./...
notifications:
  email:
    recipients:
      - devs@eventials.com
    on_success: never
    on_failure: always
